backend:
  name: git-gateway
  

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Cover Image", name: "coverImg", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}